version: '3'

services:
 payment-manager:
   command: sh dev.sh
   build: .
   volumes:
     - ./src:/app
   image: instagramtools/payment-manager:new
   ports:
   - "5000:7000"
   depends_on:
   - postgres
   links:
   - postgres:postgres
   env_file:
     - .env
   environment:
   - DEBUG=True
   - DB_NAME=postgres
   - DB_USER=postgres
   - DB_PASS=postgres
   - DB_SERVICE=postgres
   - DB_PORT=5432

 postgres:
    image: postgres:latest
    volumes:
    - db_data:/var/lib/postgresql
    ports:
    - "5432:5432"
    environment:
    - DB_NAME=postgres
    - DB_USER=postgres
    - DB_PASS=postgres

volumes:
  db_data: